name: Deploy Laravel to backadm-dmc

on:
  push:
    branches:
      - stagging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH for deployment
      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY_VPS }}

      # Step 3: Deploy Laravel
      - name: Deploy Laravel
        run: |
          ssh -p 22 -o StrictHostKeyChecking=no ${{ secrets.STAGING_SERVER_USERNAME }}@${{ secrets.STAGING_SERVER_IP }} << 'EOF'
            set -e
            # Navigate to the project directory
            cd /home/dmcdemo/public_html/backadm-dmc
            
            # Pull the latest code
            git pull origin stagging
            
            # Set ownership to ensure proper permissions
            chown -R dmcdemo:dmcdemo /home/dmcdemo/public_html/backadm-dmc
          EOF
