name: Deploy Laravel to backadm-dmc

on:
  push:
    branches:
      - stagging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: stagging

      # Step 2: Set up SSH for deployment
      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY_VPS }}

      # Step 3: Deploy Laravel application to the server
      - name: Deploy Laravel
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.STAGING_SERVER_USERNAME }}@${{ secrets.STAGING_SERVER_IP }} << 'EOF'
            set -e

            # Navigate to the project directory
            cd /home/dmcdemo/public_html/backadm-dmc

            # Ensure clean Git state for this repository
            git remote remove origin || true
            git init
            git remote add origin git@github.com:BidiptaTech/Development_DMC.git
            git fetch --all
            git reset --hard origin/stagging
            git checkout stagging

            # Set file and directory permissions
            chown -R dmcdemo:dmcdemo /home/dmcdemo/public_html/backadm-dmc

            # Install PHP dependencies
            composer install --no-dev --optimize-autoloader

            # Set file permissions
            find /home/dmcdemo/public_html/backadm-dmc -type f -exec chmod 644 {} \;  # Files
            find /home/dmcdemo/public_html/backadm-dmc -type d -exec chmod 755 {} \;  # Directories
            chmod -R 775 /home/dmcdemo/public_html/backadm-dmc/storage
            chmod -R 775 /home/dmcdemo/public_html/backadm-dmc/bootstrap/cache

            # Run Laravel Artisan commands
            php artisan config:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
            php artisan db:seed --class=CountriesTableSeeder
          EOF
