name: Deploy Laravel to backadm-dmc

on:
  push:
    branches:
      - stagging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY_VPS }}

      - name: Deploy Laravel
        run: |
          ssh -p 22 -o StrictHostKeyChecking=no ${{ secrets.STAGING_SERVER_USERNAME }}@${{ secrets.STAGING_SERVER_IP }} << 'EOF'
            cd /home/dmcdemo/public_html/backadm-dmc
            git pull origin stagging

            # Install dependencies
            composer install --no-dev --optimize-autoloader

            # Set permissions
            chmod -R 755 /home/dmcdemo/public_html/backadm-dmc
            chmod -R 775 /home/dmcdemo/public_html/backadm-dmc/storage
            chmod -R 775 /home/dmcdemo/public_html/backadm-dmc/bootstrap/cache

            # Run artisan commands
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
          EOF
